<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<<<<<<< HEAD
<testsuite hostname="CHNMCT369326L" failures="0" tests="6" name="com.testCases.LaptopFlow" time="30.733" errors="1" timestamp="31 Jul 2020 07:23:17 GMT" skipped="5">
  <testcase classname="com.testCases.LaptopFlow" name="TC_001_AppleLaptopFunctionality" time="17.239">
    <skipped/>
  </testcase> <!-- TC_001_AppleLaptopFunctionality -->
  <testcase classname="com.testCases.LaptopFlow" name="beforeMethod" time="13.292">
    <error type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException
at com.amazon.selenium.base.SeleniumBase.startApp(SeleniumBase.java:277)
at com.qa.ApplicationSpecifics.ProjectSpecificMethods.beforeMethod(ProjectSpecificMethods.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
=======
<testsuite skipped="5" hostname="CHNMCT279709L" name="com.testCases.LaptopFlow" tests="6" failures="0" timestamp="24 Jul 2020 16:54:51 GMT" time="4.695" errors="1">
  <testcase name="TC_002_AsusLaptopFunctionality" time="0.000" classname="com.testCases.LaptopFlow">
    <skipped/>
  </testcase> <!-- TC_002_AsusLaptopFunctionality -->
  <testcase name="runScenario" time="0.000" classname="com.testCases.LaptopFlow">
    <skipped/>
  </testcase> <!-- runScenario -->
  <testcase name="TC_001_AppleLaptopFunctionality" time="0.000" classname="com.testCases.LaptopFlow">
    <skipped/>
  </testcase> <!-- TC_001_AppleLaptopFunctionality -->
  <testcase name="runScenario" time="0.000" classname="com.testCases.LaptopFlow">
    <skipped/>
  </testcase> <!-- runScenario -->
  <testcase name="beforeMethod" time="4.695" classname="com.testCases.LaptopFlow">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.amazon.selenium.base.SeleniumBase.takeSnap(SeleniumBase.java:471)
at utils.Reporter.reportStep(Reporter.java:48)
at utils.Reporter.reportStep(Reporter.java:64)
at com.amazon.selenium.base.SeleniumBase.startApp(SeleniumBase.java:276)
at com.qa.ApplicationSpecifics.ProjectSpecificMethods.beforeMethod(ProjectSpecificMethods.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
>>>>>>> d609dfd1a34f36e52548cbd4859397fca6285892
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- beforeMethod -->
<<<<<<< HEAD
  <testcase classname="com.testCases.LaptopFlow" name="TC_002_AsusLaptopFunctionality" time="0.000">
    <skipped/>
  </testcase> <!-- TC_002_AsusLaptopFunctionality -->
  <testcase classname="com.testCases.LaptopFlow" name="TC_003_AcerLaptopFunctionality" time="0.000">
    <skipped/>
  </testcase> <!-- TC_003_AcerLaptopFunctionality -->
  <testcase classname="com.testCases.LaptopFlow" name="runScenario" time="0.000">
    <skipped/>
  </testcase> <!-- runScenario -->
  <testcase classname="com.testCases.LaptopFlow" name="runScenario" time="0.202">
    <skipped/>
  </testcase> <!-- runScenario -->
=======
  <testcase name="TC_003_AcerLaptopFunctionality" time="0.000" classname="com.testCases.LaptopFlow">
    <skipped/>
  </testcase> <!-- TC_003_AcerLaptopFunctionality -->
>>>>>>> d609dfd1a34f36e52548cbd4859397fca6285892
</testsuite> <!-- com.testCases.LaptopFlow -->
